#/**
#* @ClassName autologin.properties
#* @Description \uac1c\ubc1c\uc790\ub97c \uc704\ud55c \uc790\ub3d9\ub85c\uadf8\uc778 \uc124\uc815 Property(autologin.use=true\uc774\uace0 \uac1c\ubc1c\uc790 \ub85c\uce7c\ud658\uacbd\uc5d0\uc11c\ub9cc \ub3d9\uc791)
#* @Modification-Information
#* <pre>
#*    \uc218\uc815\uc77c       \uc218\uc815\uc790              \uc218\uc815\ub0b4\uc6a9
#*  ----------   ----------   -------------------------------
#*  2017. 3. 01.   SWA        \ucd5c\ucd08\uc0dd\uc131
#* </pre>
#* @author K-water \uc5c5\ubb34\uc2dc\uc2a4\ud15c \ud601\uc2e0\uc0ac\uc5c5 : SWA(\uc815\ubcf4\ud654 \ud45c\uc900)
#* @since 2017.03.01.
#* @version 1.0
#* @see
#* <pre>
#*  Copyright (C) 2017 by Unlimited K-water, All right reserved.
#* </pre>
#*/

#\uc790\ub3d9\ub85c\uadf8\uc778 \uc0ac\uc6a9\uc5ec\ubd80
autologin.use=false

#\uc790\ub3d9\ub85c\uadf8\uc778\uc744 \uc704\ud55c \uc0ac\uc6a9\uc790\uc815\ubcf4
autologin.userId=[USER_ID]
autologin.userNm=[USER_NAME]
