#/**
#* \ud504\ub85c\uc81d\ud2b8\ubcc4 \ud658\uacbd\uc124\uc815 \uc815\ubcf4 Properties
#* @ClassName hasim.properties
#* @Description hasim properties 
#* @Modification-Information
#*    \uc218\uc815\uc77c               \uc218\uc815\uc790              \uc218\uc815\ub0b4\uc6a9
#*  ----------   ----------   -------------------------------
#*  2017. 3. 01.   SWA        \ucd5c\ucd08\uc0dd\uc131
#* 
#* @author K-water \uc5c5\ubb34\uc2dc\uc2a4\ud15c \ud601\uc2e0\uc0ac\uc5c5 : SWA(\uc815\ubcf4\ud654 \ud45c\uc900)
#* @since 2017.03. 01.
#* @version 1.0
#* @see 
#* 
#*  Copyright (C) 2017 by Unlimited K-water, All right reserved.
#*/

#\uc5c5\ubb34\ubcc4 \ud504\ub85c\ud37c\ud2f0 key \uba85\uba85\uaddc\uce59
#\ud074\ub798\uc2a4\ud328\ud0a4\uc9c0\uc758 Level1\uba85.2\uba85.3\uba85.\uc758\ubbf8\uc788\ub294 \uba85\uce6d \ud615\uc2dd\uc73c\ub85c \uc791\uc131 (2,3\uc740 \uc0dd\ub7b5\uac00\ub2a5) : \uba54\uc2dc\uc9c0 ID \uaddc\uce59\uacfc \ub3d9\uc77c
#\uc608)sm.ssi.sms.sendYn=true
 
#\uc2e4\ud589\ubaa8\ub4dc (localhost, devserver, server)
run.mode=localhost
#run.mode=server

#\uc624\ub958 \uba54\uc2dc\uc9c0\ub97c \uc0c1\uc138\ud558\uac8c \ud45c\uc2dc\ud560\uc9c0 \uc5ec\ubd80 (true\uc774\uba74 \uc0c1\uc138\uc624\ub958 \uba54\uc2dc\uc9c0\uac00 \uc0ac\uc6a9\uc790\uc5d0\uac8c \ud45c\uc2dc\ub418\uba70, false\uc774\uba74 \uc0c1\uc138\uc624\ub958 \uba54\uc2dc\uc9c0\uac00 \ud45c\uc2dc\ub418\uc9c0 \uc54a\uc74c)
#\ub85c\uceec/\uac1c\ubc1c\uc11c\ubc84\uc5d0\uc11c\ub294 true, \uc6b4\uc601\uc11c\ubc84\uc5d0\uc11c\ub294 false
errmsg.show.detail=true

#\ub85c\uadf8\uc778 url
login.url=/cmmn/login

#CSRF validation\uc744 \uc0ac\uc6a9\ud560\uc9c0 \uc5ec\ubd80 (\uac1c\ubc1c\uc790\ub85c\uceec\uc740 false, \uac1c\ubc1c/\uc6b4\uc601\uc11c\ubc84\ub294 true)
csrf.validation.use=true

#AccessLog\ub97c \uc0ac\uc6a9\ud560\uc9c0 \uc5ec\ubd80 (\uac1c\ubc1c\uc790\ub85c\uceec\uc740 false, \uac1c\ubc1c/\uc6b4\uc601\uc11c\ubc84\ub294 true)
accesslog.use=false

#Exception\uc5d0 \ub300\ud55c AccessLog\ub97c \uc0ac\uc6a9\ud560\uc9c0 \uc5ec\ubd80
accesslog.exception.use=true

#\uc0ac\uc6a9\uc790 Action\uc5d0 \ub300\ud55c AccessLog\ub97c \uc0ac\uc6a9\ud560\uc9c0 \uc5ec\ubd80
accesslog.action.use=false

#\uc911\ubcf5\ub85c\uadf8\uc778 \ubc29\uc9c0 \uc801\uc6a9 \uc5ec\ubd80 (true\uc774\uba74 \uc11c\ub85c \ub2e4\ub978 IP\uc5d0\uc11c \uc911\ubcf5 \ub85c\uadf8\uc778 \ud5c8\uc6a9)
login.duplication.allow=true

#\uad00\ub9ac\uc790\ub85c\uadf8\uc778 \uc2dc \ud5c8\uc6a9 IP \uac80\uc0ac \uc5ec\ubd80 (true\uc774\uba74 \ub4f1\ub85d\ub41c IP \uac80\uc0ac)
login.admin.ip.check=false

#\uad8c\ud55c \uc801\uc6a9\uc5ec\ubd80 \uc124\uc815(true\uc774\uba74 \uad8c\ud55c\uc801\uc6a9, false\uba74 \uc801\uc6a9\ud558\uc9c0 \uc54a\uace0 \ubaa8\ub4e0 \uad8c\ud55c\uc73c\ub85c \ucc98\ub9ac\ud568.)
authority.apply=false

#\uc77c\uc815 \ud69f\uc218 \uc774\uc0c1 \ud328\uc2a4\uc6cc\ub4dc \uc785\ub825 \uc624\ub958\uac00 \ubc1c\uc0dd\ud55c \uacbd\uc6b0 \uc7ac\ub85c\uadf8\uc778 \uc9c0\uc5f0 \uc2dc\uac04 (\ubd84\ub2e8\uc704 \uc124\uc815)
login.wait.time = 2

#\uc5b4\ud50c\ub9ac\ucf00\uc774\uc158 \ube44\uc815\uc0c1 \uc885\ub8cc\uc5d0 \ub300\ud55c \uc790\ub3d9 \ub85c\uadf8\uc544\uc6c3 \ucc98\ub9ac\ub97c \uc704\ud55c \uae30\uc900 \uc2dc\uac04(\ubd84) : \uc774 \uc2dc\uac04\ub9cc\ud07c \uc9c0\ub09c \uacbd\uc6b0 \ub85c\uadf8\uc544\uc6c3 \ucc98\ub9ac
autologout.over.mimute=30

##############################################################################
# File Upload/Download \uc815\ubcf4
##############################################################################
# WebSquare Config \ud30c\uc77c\uc5d0\uc11c \uad00\ub9ac\uc911
#FileUpload size (\ub2e8\uc704 MB)
global.fileupload.size=50
global.fileupload.excludeFileExt=jsp:php:asp:exe:c:cc:com:css:js:cgi:dat:jar:java:class:lib:log:bak:php3:phtml:reg:vbs

#File \uc800\uc7a5\uc2dc \ud30c\uc77c\uba85\uc5d0 \uc2dc\uac04\uc744 \ud45c\uc2dc\ud560\uc9c0 \uc5ec\ubd80
global.fileupload.appendTime=true

##############################################################################
# File Repository \uc815\ubcf4 : \uc5c5\ubb34\ubcc4\ub85c \ud558\uc704 \ud3f4\ub354\ub97c \ub9cc\ub4e4\uace0 \ud30c\uc77c\uc744 \uc800\uc7a5\ud55c\ub2e4.
##############################################################################
#FileUpload (\uc800\uc7a5\uc18c \ud328\uc2a4)
#LOCAL
global.fileupload.oldPath=[FILE_TEMP_PATH]
global.fileupload.tempPath=[FILE_TEMP_PATH]
global.fileupload.path=[FILE_UPLOAD_PATH]
global.imgFileupload.path=[IMAGE_UPLOAD_PATH]
global.filedownload.path=[FILE_DOWNLOAD_PATH]
global.session.share.tempPath=[SESSION_SHARE_PATH]
global.session.remove.tempPath=[SESSION_REMOVE_PATH]

#SERVER
#global.fileupload.oldPath=[FILE_UPLOAD_PATH]
#global.fileupload.tempPath=[FILE_TEMP_PATH]
#global.fileupload.path=[FILE_UPLOAD_PATH]
#global.imgFileupload.path=[IMAGE_UPLOAD_PATH]
#global.filedownload.path=[FILE_DOWNLOAD_PATH]
#global.session.share.tempPath=[SESSION_SHARE_PATH]
#global.session.remove.tempPath=[SESSION_REMOVE_PATH]

#ECS
#global.fileupload.ecsPath=[FILE_UPLOAD_PATH]
global.fileupload.ecsPath=[FILE_UPLOAD_PATH]

#\ucca8\ubd80\ud30c\uc77c\uacf5\uc720\uad6c\ubd84 (hrm\uc740 \ud0c0\uc2dc\uc2a4\ud15c\uacfc \ucca8\ubd80\ud30c\uc77c \uacf5\uc720\uac00 \uc5c6\uae30 \ub54c\ubb38\uc5d0 \uc81c\uc678\ud568, \ud544\uc694\uc2dc \uc81c\uc77c \ub9c8\uc9c0\ub9c9\uc5d0 \ucd94\uac00\ud560 \uac83)
#\uc2dc\uc2a4\ud15c\uad6c\ubd84\uc21c\uc11c : scm(0),adt(1),cms(2),fms(3),lws(4),mgt(5),stg(6),wcb(7),wfm(8),wqe(9),wri(10),wro(11),hrm(12),law(13)
#\ucc98\ub9ac\uac12 \uc124\uc815 : 0 \uacf5\uc720\uc548\ud568, 1 \uacf5\uc720\ud568 (default\uac12\uc740 scm\uc740 \ud56d\uc0c1\uacf5\uc720\ub85c \uc124\uc815\ud568)
#\ucca8\ubd80\ud30c\uc77c \ub370\uc774\ud130 \uc870\ud68c\uc2dc \uc2dc\uc2a4\ud15c\uad6c\ubd84\ucf54\ub4dc\uc5d0 \ub530\ub77c \uacf5\uc720\uac12 \ud655\uc778 \ud6c4 \ucc98\ub9ac\ud568 
#\uac1c\ubc1c\uc11c\ubc84
global.fileupload.shr=[FILE_SHARE_FLAGS]

#\uc6b4\uc601\uc11c\ubc84
#\uacf5\ud1b5
#global.fileupload.shr=[FILE_SHARE_FLAGS]
#\uc7ac\ubb34(FMS)
#global.fileupload.shr=[FILE_SHARE_FLAGS]
#\uac74\uc124(CMS)
#global.fileupload.shr=[FILE_SHARE_FLAGS]
#\uc2dc\uc124(WFM)
#global.fileupload.shr=[FILE_SHARE_FLAGS]
#\ub098\uba38\uc9c0 \uc2dc\uc2a4\ud15c(\uc5c5\ubb34\ub2e8 \ud655\uc778\ud544\uc694\ud568)
#global.fileupload.shr=[FILE_SHARE_FLAGS]

##############################################################################
# Fasoo \uc815\ubcf4 : DRM\uc744 \uc124\uc815\ud55c\ub2e4.
##############################################################################
#LOCAL
fasoo.server.installPath=[FASOO_INSTALL_PATH]
fasoo.server.encFilePath=[FASOO_ENC_PATH]
fasoo.server.decFilePath=[FASOO_DEC_PATH]
#SERVER
#fasoo.server.installPath=[FASOO_INSTALL_PATH]
#fasoo.server.installPath=[FASOO_INSTALL_PATH]
fasoo.server.id=[FASOO_SERVER_ID]
fasoo.server_yellow.id=[FASOO_SERVER_ID]
#fasoo.server.encFilePath=[FASOO_ENC_PATH]
#fasoo.server.decFilePath=[FASOO_DEC_PATH]
#fasoo.server.gubun=dev
fasoo.server.gubun=prod
kw.drm.install=Y
#DRM \uc801\uc6a9 \ud655\uc7a5\uc790
kw.drm.arrowExt=txt:dwg:rtf:xlsx:pptx:docx:pdf:xls:ppt:doc:hwp:hwpx

##############################################################################
# Batch File \uc815\ubcf4 (\uc5c5\ubb34\ubcc4\ub85c \ud558\uc704 \ud3f4\ub354\ub97c \ub9cc\ub4e4\uace0 \uc0ac\uc6a9 \uac00\ub2a5)
##############################################################################
#global.batch.input.path=[BATCH_INPUT_PATH]
#global.batch.output.path=[BATCH_OUTPUT_PATH]

##############################################################################
# \uc774\uc911\ud654 \uc11c\ubc84\uc5d0\uc11c \uc2a4\ucf00\uc974\ub7ec\ub294 Active-Standby \ubc29\uc2dd\uc73c\ub85c \ucc98\ub9ac\ub418\ub3c4\ub85d \uad6c\uc131\ud55c\ub2e4.
# \uc2a4\ucf00\uc974\ub9c1\uc774 \uc2e4\ud589\ub418\ub294 \uba54\uc778/\uc11c\ube0c \uc11c\ubc84\uc758 IP \uc815\ubcf4(\ub0b4\ubd80IP\ub85c \uc124\uc815\ud574\uc57c\ud568)
##############################################################################
# \uc774\uc911\ud654 \uc11c\ubc84\uc5d0\uc11c \uc2a4\ucf00\uc974\ub7ec \uc2e4\ud589 \uac80\uc0ac \ubaa8\ub4dc : none\ub294 \uac1c\ubc1c\ubaa8\ub4dc, single\uc740 \ud2b9\uc815\uc11c\ubc84\uc5d0\uc11c\ub9cc \uc2e4\ud589, cluster\ub294 \uc0c1\ub300 \uc11c\ubc84\uac00 \uc8fd\uc740 \uacbd\uc6b0 \uc790\uc2e0 \uc11c\ubc84\uc5d0\uc11c \uc2e4\ud589
#schedule.excute.checkEcecuteMode=none
# \uc11c\ubc84\uc5d0\uc11c \ud2b9\uc815 \ucee8\ud14c\uc774\ub108 \uc2a4\ucf00\uc974\ub7ec \uc2e4\ud589 \uac80\uc0ac \uc5ec\ubd80 : \ud2b9\uc815 \ucee8\ud14c\uc774\ub108\uc5d0\uc11c\ub9cc \uc2e4\ud589\ud560\uc9c0 \uac80\uc0ac \uc5ec\ubd80\ub85c no\ub294 \uac80\uc0ac\uc548\ud568, yes\ub294 \uac80\uc0ac\ud568(\ub3d9\uc77c \uc5b4\ud50c\ub9ac\ucf00\uc774\uc158\uc774 \ub2e4\uc911 \ucee8\ud14c\uc774\ub108\uc5d0 \uc2e4\ud589\ub418\ub294 \uacbd\uc6b0)
#schedule.excute.checkContainerYn=no
# \uc2a4\ucf00\uc974\ub9c1 \uc11c\ubc84 \uba54\uc778IP
#schedule.excute.serverMainIp=[SERVERIP]
# \uc2a4\ucf00\uc974\ub9c1 \uc11c\ubc84 \uc11c\ube0cIP
#schedule.excute.serverSubIp=[SERVERIP]
# \uc2a4\ucf00\uc904\ub9c1 \uc11c\ubc84(WAS\uc811\uadfc) PORT
#schedule.excute.wasPort=8091
# \uc2a4\ucf00\uc904\ub9c1 \uc11c\ubc84(WAS\uc811\uadfc) \uac80\uc0ac URL (IP, PORT \uc81c\uc678)
#schedule.excute.checkUrl=health.jsp
# \uc2a4\ucf00\uc904\ub9c1 \uc11c\ubc84(WAS\uc811\uadfc) \uc7ac\uac80\uc0ac \ud69f\uc218
#schedule.excute.recheckCount=3

##############################################################################
# \uc774\uc911\ud654 \uc11c\ubc84 \uac04 RMI \ud1b5\uc2e0\uc744 \uc704\ud55c \uc815\ubcf4
##############################################################################
# \uc774\uc911\ud654 \uc11c\ubc84\uc5d0\uc11c RMI \uc2e4\ud589 \uac80\uc0ac \ubaa8\ub4dc : none\ub294 \uac1c\ubc1c\ubaa8\ub4dc, single\uc740 single server, cluster\ub294 cluster server

##############################################################################
# \uc554\ud638\ud654 \uc815\ubcf4 
##############################################################################


##############################################################################
# websocket push server \uc815\ubcf4
##############################################################################
#websocket.push.server.port=8081

##############################################################################
# Initech iniplugin \uc815\ubcf4 
##############################################################################
#\uc124\uce58\uc704\uce58
#iniplugin.install.path=[INIPLUGIN_INSTALL_PATH]
#iniplugin.properties \ud30c\uc77c \uc704\uce58\ub85c uiAdaptor \ub4f1 iniplugin\uc0ac\uc6a9 \uc2dc \ud544\uc218 \uc784
#iniplugin.properties=[INIPLUGIN_PROPERTIES_PATH]
#\uc554\ud638\ud654 \ub610\ub294 \uc804\uc790\uc11c\uba85 \ub370\uc774\ud130 \uc804\uc1a1 \uc2dc \ub370\uc774\ud130\uba85
#iniplugin.data.name=INIpluginData
#XPLATFORM\uc5d0\uc11c \uc804\uccb4 \ub370\uc774\ud130 \uc554\ud638\ud654\ud558\uc5ec \uc804\uc1a1 \uc2dc \ub370\uc774\ud130\uba85
#xpiniplugin.data.name=InitechXPData
#XPLATFORM\uc5d0\uc11c \uc804\uccb4 \ub370\uc774\ud130 \uc554\ud638\ud654\ud558\uc5ec \uc804\uc1a1 \uc2dc \ub370\uc774\ud130 \ud0c0\uc785 : XML or BIN
#xpiniplugin.data.type=binType

##############################################################################
# OZ Report \uc815\ubcf4
##############################################################################
#OZ Viewer Download Server
#oz.download.server=http://[OZIP]/ozrviewer/
#OZ XTransferX Download Server
#oz.download.ztransferx.server=http://[OZIP]:8093/ozrviewer/
#OZ Viewer Download js
#oz.download.js=http://[OZIP]:8093/ozrviewer/
#OZ Viewer Download Port
#oz.download.port=8093
#Report Server Url
#oz.connection.servlet=http://[OZIP]:8093/server
#Report Background Vertical Image - no use
##oz.background.image=/images/report/background.gif
#Report Background Horizontal Image  - no use
##oz.background-horizon.image=/images/report/background-horizon.gif
#Report Top Logo Image
#oz.toplogo.image=/images/report/hwrc-logo.png
#Report Stamp Image
#oz.stamp.image=/images/report/hwrc-stamp.gif

##Local Server
#OZ Viewer Download Server
#oz.download.server=http://[LOCALIP]:8080/ozreport/ozrviewer/
#OZ XTransferX Download Server
#oz.download.ztransferx.server=http://[LOCALIP]:8080/ozrviewer/
#OZ Viewer Download js
#oz.download.js=http://[LOCALIP]:8080/ozreport/ozrviewer/
#OZ Viewer Download Port
#oz.download.port=80
#Report Server Url
#oz.connection.servlet=http://[LOCALIP]:8080/ozreport/server
#Report Background Vertical Image - no use
##oz.background.image=/images/report/background.gif
#Report Background Horizontal Image - no use
##oz.background-horizon.image=/images/report/background-horizon.gif
#Report Top Logo Image
#oz.toplogo.image=/images/report/hwrc-logo.png
#Report Stamp Image - no use
##oz.stamp.image=/images/report/hwrc-stamp.gif

##############################################################################
# \uc778\uc99d\uc11c \ubc0f \uc804\uc790\uc11c\uba85 \uc815\ubcf4
# \uad00\ub828 \ubaa8\ub4c8\uc774 \uc124\uce58\ub418\uc9c0 \uc54a\uc544 \uc124\uce58\ub41c \uc11c\ubc84\ub85c \uc704\uc784\ucc98\ub9ac \ud558\ub3c4\ub85d \uad6c\uc131\uc740 HMPG\ub9cc \ud574\ub2f9 (\ub0b4\ubd80\ud3ec\ud138\uc5d0\uc11c \uc704\uc784 \uc694\uccad)
##############################################################################


##############################################################################
# SSO \uc815\ubcf4 -->OASIS Login Check 
##############################################################################
# SSO \uc815\ubcf4
fasoo.sso.key=[SSO_KEY]
# OASIS \ub370\uc774\ud130 \uc720\ud6a8\uc131 \uccb4\ud06c URL
oasis.data.validation.url=http://[OASIS_DOMAIN]:8080/support/sso/dbServerTime.do
# OASIS \uc138\uc158 \uccb4\ud06c URL
oasis.sessionCheck.url=http://[OASIS_DOMAIN]:8080/support/sso/oasisSessionKey.do
# OASIS \uc0ac\uc6d0\ubd80\uc7ac\uc911 URL
oasis.checkUserAbsType.url=http://[OASIS_DOMAIN]/custom/org/setting/checkUserAbsType.jsp
# OASIS \uc54c\ub9ac\ubbf8 \ud638\ucd9c URL
oasis.sendOasisNotify.url=http://[OASIS_DOMAIN]/jsp/notifyAdapter.jsp
##############################################################################
# EAI \uc5f0\uacc4 \uc815\ubcf4
##############################################################################
#Local
#mmsEai.url=http://[EAIIP]:8094/indigo/eai/KWaterCommonRestProvider
#daonMailEAI.url=http://[EAIIP]:8094/indigo/eai/KWaterCommonRestProvider
sapEai.url=http://[EAIIP]:8094/indigo/eai/KWaterSapCommonProvider

#Server
mmsEai.url=http://[EAI_DOMAIN]:8094/indigo/eai/KWaterCommonRestProvider
daonMailEAI.url=http://[EAI_DOMAIN]:8094/indigo/eai/KWaterCommonRestProvider
#sapEai.url=http://[EAI_DOMAIN]:8094/indigo/eai/KWaterSapCommonProvider

global.smtp=[SMTP_DOMAIN]
##############################################################################
# FMS XML \uc5f0\uacc4 \ub514\ub809\ud1a0\ub9ac
##############################################################################
#fms.interface.dir=[FMS_INTERFACE_PATH]
fms.interface.dir=[FMS_INTERFACE_PATH]
##############################################################################
# FMS \uc778\uc99d\uc11c \uac80\uc99d\uc11c\ubc84
##############################################################################
fms.demonserver.ip=[FMSIP]
fms.demonserver.port=7900

# SAP JCO \ud1b5\uc2e0 property Local
#jco.direct.call=N
#jco.clean.time=0
#jco.client.ashost=[SAPIP]
#jco.client.sysnr=[SAPSYSNR]
#jco.client.client=[SAPCLIENT]
#jco.client.user=[SAPUSER]
#jco.client.passwd=[SAPPASSWORD]
#jco.client.lang=KO
#jco.destination.max_get_client_time=60000
#jco.destination.pool_capacity=30
#jco.destination.peak_limit=100

# SAP JCO \ud1b5\uc2e0 property Server
jco.direct.call=N
jco.clean.time=10
#jco.client.mshost=[SAPIP]
#jco.client.msserv=3601
jco.client.ashost=[SAPIP]
jco.client.sysnr=[SAPSYSNR]
jco.client.gwhost=[SAPIP]
jco.client.gwserv=[SAPGWSERV]
jco.client.group=[SAPGROUP]
jco.client.r3name=[SAPR3NAME]
jco.client.user=[SAPUSER]
jco.client.passwd=[SAPPASSWORD]
jco.client.client=[SAPCLIENT]
jco.client.lang=KO
jco.destination.max_get_client_time=60000
jco.destination.pool_capacity=20
jco.destination.peak_limit=100

#\uc6f9 \uc54c\ub9ac\ubbf8 url
noti.send.type=WEB;HANDY
#noti.send.url=https://[NOTI_DOMAIN]/api/ntcn/publishNtcn.do
#noti.recv.check.url=https://[NOTI_DOMAIN]/api/ntcn/retrieveNtcn.do 
noti.send.url=https://[NOTI_DOMAIN]/api/ntcn/publishNtcn.do
noti.recv.check.url=https://[NOTI_DOMAIN]/api/ntcn/retrieveNtcn.do 

#synapDocView
#synapDocViewProxy.url=https://[DOC_VIEWER_DOMAIN]
synapDocViewProxy.url=https://[DOC_VIEWER_DOMAIN]
synapDocView.apiKey=[SYNAP_API_KEY]
synapDocView.apiKey.useYn=Y
